Repository danhdoan/intel-gaudi-lab, pull requests merged in 2025-04, with the labels that each got.

#2 DONE feat/1 setup project base
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  apps/__init__.py
  apps/app.py
  data/.gitkeep
  libs/__init__.py
  libs/cli/__init__.py
  libs/cli/cli_parser.py
  libs/configs/__init__.py
  libs/configs/configs.py
  libs/utils/__init__.py
  libs/utils/averager/__init__.py
  libs/utils/averager/averager.py
  libs/utils/common.py
  libs/utils/logger_utils.py
  libs/utils/time_utils.py
  models/.gitkeep
  pyproject.toml
  requirements.txt
  scripts/source_env.sh
  setup.py
  uv.lock
Labels: feature

#8 DONE feat/4 setup virtual environment for habana framework
  Makefile
  README.md
  compose.yml
  example.env
Labels: feature

#13 Exp/9 Impl. Stable Diffusion 2.1 Inference module
  apps/app.py
  compose.yml
  experimentals/inference_stable_diffusion.py
  experimentals/run.sh
  experimentals/stable_diffusion_2_1_app.py
  libs/cli/cli_parser.py
  libs/configs/__init__.py
  libs/configs/configs.py
  libs/utils/averager/averager.py
  libs/utils/common.py
  libs/utils/logger_utils.py
  libs/utils/time_utils.py
  public/assets/styles.css
  public/index.html
  public/script.js
  pyproject.toml
  requirements.txt
  scripts/source_env.sh
  uv.lock
Labels: experimental

#20 EXP #18 - Setup Worker to Handle Mass Requests
  multi-workers/README
  multi-workers/benchmark.js
  multi-workers/nginx.conf
  multi-workers/start.sh
  multi-workers/worker.py
Labels: experimental

#22 Enhance/21 restructure experimentals folder
  experimentals/image_generation/README.md
  experimentals/image_generation/inference_stable_diffusion.py
  experimentals/image_generation/public/assets/styles.css
  experimentals/image_generation/public/index.html
  experimentals/image_generation/public/script.js
  experimentals/image_generation/run.sh
  experimentals/image_generation/src/macro.py
  experimentals/image_generation/src/pipeline_loader.py
  experimentals/image_generation/src/type.py
  experimentals/image_generation/stable_diffusion_app.py
  experimentals/multi_workers/README.md
  experimentals/multi_workers/benchmark.js
  experimentals/multi_workers/nginx.conf
  experimentals/multi_workers/start.sh
  experimentals/multi_workers/worker.py
  experimentals/run.sh
  experimentals/stable_diffusion/__init__.py
Labels: enhancement

#25 WIP #23 - Experiment Image to Video with Diffusion Model
  experimentals/image_to_video/image_to_video_generation.py
  experimentals/image_to_video/run_img2vid.sh
Labels: experimental

#30 Exp/28 fe be integration for video generation workflow
  experimentals/image_to_video/README.md
  experimentals/image_to_video/image_to_video_generation_app.py
  experimentals/image_to_video/public/assets/styles.css
  experimentals/image_to_video/public/index.html
  experimentals/image_to_video/public/script.js
  experimentals/image_to_video/run_app.sh
  experimentals/image_to_video/run_img2vid.sh
  experimentals/image_to_video/src/macro.py
  experimentals/image_to_video/src/pipeline_loader.py
  experimentals/image_to_video/src/process_video.py
  experimentals/image_to_video/src/type.py
  requirements.txt
Labels: experimental

#32 WIP #31 - refactor path handling and add config docs for image generation app
  experimentals/image_generation/README.md
  experimentals/image_generation/public/index.html
  experimentals/image_generation/run_app.sh
  experimentals/image_generation/src/macro.py
  experimentals/image_generation/stable_diffusion_app.py
Labels: bug

#33 WIP #24 improve docker container environment for development
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  compose.yml
  example.env
  pyproject.toml
  requirements.txt
Labels: enhancement

#34 WIP #3 - add gaudi_inference_pipeline to libs
  libs/generative_ai/image_generation/stable_diffusion/__init__.py
  libs/generative_ai/image_generation/stable_diffusion/gaudi_inference_pipeline.py
  libs/generative_ai/image_generation/stable_diffusion/pipeline_loader.py
  libs/generative_ai/image_generation/stable_diffusion/registry.py
Labels: experimental

#38 DONE #35 - Experiment Image to Video with SVD
  experimentals/image_to_video/image_to_video_generation_with_svd.py
  experimentals/image_to_video/run_img2vid_svd.sh
Labels: experimental

#39 DONE #36 - Refactor Image Generation Pipeline in Webapp
  apps/image_generation/README.md
  apps/image_generation/image_generation_webapp.py
  apps/image_generation/public/assets/styles.css
  apps/image_generation/public/index.html
  apps/image_generation/public/script.js
  apps/image_generation/run_app.sh
  apps/image_generation/src/type.py
  libs/utils/image_utils.py
Labels: deployment

#43 WIP #42 - Experiment with Image Captioning
  experimentals/image_captioning/image_captioning_app.py
  experimentals/image_captioning/public/assets/styles.css
  experimentals/image_captioning/public/index.html
  experimentals/image_captioning/public/script.js
  experimentals/image_captioning/run_app.sh
  experimentals/image_captioning/src/pipeline_loader.py
  experimentals/image_captioning/src/registry.py
  experimentals/image_captioning/src/type.py
  requirements.txt
Labels: experimental
